accessControl: {}
api:
  enabled: true
  key: 650B578D96B84425A50114A12EEABF42
appearance: {}
cura: {}
feature:
  swallowOkAfterResend: false
printerParameters:
  invertAxes:
  - x
  movementSpeed: {}
serial:
  baudrate: 250000
  port: /dev/ttyACM0
  timeout: {}
server:
  firstRun: false
system: {}
temperature:
  profiles:
  - bed: '90'
    extruder: '240'
    name: ABS
  - bed: 60
    extruder: '190'
    name: PLA
terminalFilters:
- name: Suppress M105 requests/responses
  regex: '(Send: M105)|(Recv: ok T:)'
- name: Suppress M27 requests/responses
  regex: '(Send: M27)|(Recv: SD printing byte)'
- name: Suppress GCode
  regex: '(Send: N)|(Recv: ok$)'
webcam:
  snapshot: http://ptarmigan.jaeho-song.com:8088/?action=snapshot
  stream: http://ptarmigan.jaeho-song.com:8088/?action=stream
